# Generated by Django 4.0.3 on 2022-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
