# Generated by Django 4.0.3 on 2022-04-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
