# Generated by Django 4.0.2 on 2022-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Smartphone', max_length=50, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
