# Generated by Django 4.0.2 on 2022-03-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('reclamação', models.TextField(verbose_name='Reclamação')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('data_pergunta', models.DateTimeField(verbose_name='Data Resposta')),
            ],
        ),
    ]
