# Generated by Django 4.0.2 on 2022-03-16 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_reclamacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='data_resposta',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 16, 45, 7, 935421), verbose_name='Data Resposta'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='data_pergunta',
            field=models.DateTimeField(verbose_name='Data Pergunta'),
        ),
    ]
