# Generated by Django 4.0.2 on 2022-03-16 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_reclamacao_data_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='data_resposta',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 16, 47, 29, 40388), null=True, verbose_name='Data Resposta'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='resposta',
            field=models.TextField(null=True, verbose_name='Resposta'),
        ),
    ]
