# Generated by Django 4.0.2 on 2022-03-16 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_reclamacao_data_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='data_pergunta',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 16, 48, 26, 269178), verbose_name='Data Pergunta'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='data_resposta',
            field=models.DateTimeField(null=True, verbose_name='Data Resposta'),
        ),
    ]
