# Generated by Django 4.0.2 on 2022-03-22 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_reclamacao_data_pergunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='data_pergunta',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 15, 14, 13, 458512), verbose_name='Data Pergunta'),
        ),
    ]
