# Generated by Django 4.0.2 on 2022-03-30 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_favorito_data_adicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='data_adicao',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 9, 28, 0, 62207), verbose_name='Data da Adição na lista'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_favorito',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='data_pergunta',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 9, 28, 0, 61210), verbose_name='Data Pergunta'),
        ),
    ]
