# Generated by Django 4.0.2 on 2022-03-30 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_alter_favorito_data_adicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='data_pergunta',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 9, 31, 42, 198587), verbose_name='Data Pergunta'),
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
