# Generated by Django 4.0.2 on 2022-04-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_reclamacao_data_pergunta_carrinho'),
        ('loja', '0018_alter_favorito_data_adicao_and_more'),
    ]

    operations = [
    ]
