# Generated by Django 4.0.2 on 2022-04-01 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_merge_20220401_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='data_adicao',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 15, 56, 8, 968821), verbose_name='Data da Adição na lista'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='data_pergunta',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 15, 56, 8, 967824), verbose_name='Data Pergunta'),
        ),
    ]
