# Generated by Django 4.0.3 on 2022-04-01 19:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0022_alter_favorito_data_adicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 4, 1, 16, 35, 7, 673728), verbose_name='Data da compra')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='favorito',
            name='data_adicao',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 16, 35, 7, 673728), verbose_name='Data da Adição na lista'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='data_pergunta',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 16, 35, 7, 672731), verbose_name='Data Pergunta'),
        ),
        migrations.CreateModel(
            name='CompraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.compra')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
