# Generated by Django 4.0.2 on 2022-03-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='E-mail')),
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Questão'),
        ),
    ]
