# Generated by Django 4.0.2 on 2022-03-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_cadastro_alter_question_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
    ]
